services:
  web:
    container_name: nekosanq.net
    build:
      context: .
      target: ${BUILD_TARGET:-development}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
